### ISSUE TITLE
Render `if` conditions in HTML output

### ISSUE THREAD

**Issue by Vitineth** [Vitineth/kaitai_struct_compiler#2]
Currently conditionals are not represented at all in the spec. For this input

```yaml

      - type: b5
        if: enable_dhcp == true
        doc: Used to skip 5 bits if enable_dhcp is set to true

      - id: program_default_gateway
        type: b1
        doc: Program Default gateway
        if: enable_dhcp == false

```

It produces 

![image](https://github.com/Vitineth/kaitai_struct_compiler/assets/9435503/380b1ddd-984d-4636-bcb1-d90beb51e31b)

Which does not inform at all about the if. This needs some sort of representation but may need some thoughts on the best way to show this
